//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST10114615_PROG7312_POE_TASK_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentifyScore
    {
        public int Id { get; set; }
        public int Time { get; set; }
        public string Name { get; set; }
        public int Correct { get; set; }
        public int Score { get; set; }
    }
}
